name: Build and publish releases

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: 18

jobs:
  publish-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install

      - name: Publish
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publish-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install

      - name: Publish
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publish-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install

      - name: Publish on arm
        run: yarn run publish -p darwin -a arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish on x64
        run: yarn run publish -p darwin -a x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}